"""Optional evidence and claim creation hooks for source candidates.

Produces EvidenceItems and source-usefulness Claims from a scored
SourceCandidate.  These are lightweight wrappers around the existing
evidence layer — no LLM, no network calls.

The evidence item represents the *discovery event* (a structured observation
that the source exists and has a given quality score).  The claim represents
the assertion that the source is useful for a given domain.

Both are PROPOSED by default.  Nothing is auto-approved or auto-promoted.

Usage::

    from data.scout.schema import normalize_source_candidate
    from data.scout.scorer import score_source_candidate
    from data.scout.evidence_hooks import (
        evidence_from_candidate,
        source_claim_from_candidate,
    )
    from ml.evidence.store import ClaimStore

    candidate = normalize_source_candidate({...})
    score     = score_source_candidate(candidate)

    ev    = evidence_from_candidate(candidate, score)
    claim = source_claim_from_candidate(candidate, score)

    store = ClaimStore()
    store.add_evidence(ev)
    store.add_claim(claim)
    store.link_evidence(claim.claim_id, ev.evidence_id)
"""
from __future__ import annotations

from ml.evidence.schema import (
    Claim,
    ClaimType,
    EvidenceItem,
    EvidenceSourceType,
)
from data.scout.schema import SourceCandidate


def evidence_from_candidate(
    candidate: SourceCandidate,
    score:     float,
) -> EvidenceItem:
    """Create a discovery EvidenceItem from a scored SourceCandidate.

    The evidence item records the discovery of the source, its key metadata,
    and the computed usefulness score as structured data.

    Args:
        candidate: A normalized SourceCandidate.
        score:     The pre-computed usefulness score (0–1).

    Returns:
        A new EvidenceItem with source_type=SOURCE_REGISTRY.
    """
    return EvidenceItem.new(
        source_type     = EvidenceSourceType.SOURCE_REGISTRY,
        source_ref      = f"scout:{candidate.source_id}",
        summary         = (
            f"Source candidate '{candidate.name}' discovered via source scout. "
            f"Usefulness score: {score:.2f}. "
            f"Category: {candidate.category}. "
            f"Official: {candidate.official_source}. "
            f"Free tier: {candidate.free_tier}. "
            f"Acquisition: {candidate.acquisition_method}."
        ),
        structured_data = {
            "source_id":          candidate.source_id,
            "name":               candidate.name,
            "url":                candidate.url,
            "category":           candidate.category,
            "acquisition_method": candidate.acquisition_method,
            "auth_required":      candidate.auth_required,
            "free_tier":          candidate.free_tier,
            "official_source":    candidate.official_source,
            "update_cadence":     candidate.update_cadence,
            "asset_types":        candidate.asset_types,
            "data_types":         candidate.data_types,
            "usefulness_score":   score,
        },
    )


def source_claim_from_candidate(
    candidate:  SourceCandidate,
    score:      float,
    useful_for: str | None = None,
) -> Claim:
    """Create a source-usefulness Claim from a scored SourceCandidate.

    The claim follows the evidence naming convention::

        source:<source_id>  is_useful_for  domain:<category>

    Confidence is set to the usefulness score.  Status is PROPOSED.

    Args:
        candidate:  A normalized SourceCandidate.
        score:      The pre-computed usefulness score (0–1); used as confidence.
        useful_for: Optional domain override.  If not given, the candidate's
                    category is used (e.g. "macro", "price").

    Returns:
        A new Claim in PROPOSED status.
    """
    domain = useful_for or candidate.category

    return Claim.new(
        claim_type        = ClaimType.SOURCE_USEFULNESS,
        subject           = f"source:{candidate.source_id}",
        predicate         = "is_useful_for",
        obj               = f"domain:{domain}",
        confidence        = round(min(max(score, 0.0), 1.0), 4),
        uncertainty_notes = (
            f"Score derived from scout heuristics only — not from empirical testing. "
            f"Acquisition method: {candidate.acquisition_method}. "
            f"Auth required: {candidate.auth_required}."
        ),
        tags              = ["scout", candidate.category, candidate.acquisition_method],
        notes             = (
            f"Auto-generated by source scout for '{candidate.name}'. "
            "Review and promote to SUPPORTED only after empirical validation."
        ),
    )
